### ISSUE TITLE
Accessing User Data

### ISSUE THREAD

**Issue by mcnamee** [lucj/sails-oauth2-api#10]
Hi,
Once I've authenticated via token exchange, within Sails, how can I access the current user's _id or email address? Eg. is it saved in a session?

**Comment by gridpocketuser** [comment]
Hi mcnamee,
in the oauthBearer.js policy, the user retrieved is added in the request (req.user = user).

**Comment by mcnamee** [comment]
Thanks @gridpocketuser I realised I wasn't covering the routes in question with oauth2 - once I did that I can access user credentials with req.user
