### ISSUE TITLE
error 'token' data to long on mysql

### ISSUE THREAD

**Issue by yudapc** [lucj/sails-oauth2-api#7]
when I'm using mysql, I have error 'token' data to long. Because in mysql string/varchar max length is 255.

[Solution]
So, I just change on file api/models/AccessToken.js line 27 
    `values.token = UtilsService.uid(255);`

**Comment by lucj** [comment]
Great, I'll update this, unless you want to do a PR with this change. There
might be some other token with this restriction then.
Thanks a lot,
Luc

On Mon, Sep 7, 2015 at 1:46 PM, Yuda Cogati notifications@github.com
wrote:

> when I'm using mysql, I have error 'token' data to long. Because in mysql
> string/varchar max length is 255.
> So, I just change on file api/models/AccessToken.js line 27
> values.token = UtilsService.uid(255);
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lucj/sails-oauth2-api/issues/7.

## 

Luc Juggery - https://about.me/lucjuggery

**Comment by yudapc** [comment]
I have fix that and already create pull requst ;)

**Comment by lucj** [comment]
Sorry, did not see the email before :)
Thanks a lot

On Mon, Sep 7, 2015 at 1:56 PM, Yuda Cogati notifications@github.com
wrote:

> I have fix that and already create pull requst ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lucj/sails-oauth2-api/issues/7#issuecomment-138278817
> .

## 

Luc Juggery - https://about.me/lucjuggery

**Comment by yudapc** [comment]
Ok bro
